# Generated by Django 5.1.5 on 2025-07-14 04:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_channels',
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_contact_groups',
            },
        ),
        migrations.CreateModel(
            name='CoreFormCustomFormPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('order_number', models.FloatField( default=1.0)),
            ],
            options={
                'db_table': 'core_form_custom_form_panels',
            },
        ),
        migrations.CreateModel(
            name='CoreFormCustomFormStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('step_number', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'core_form_custom_form_steps',
            },
        ),
        migrations.CreateModel(
            name='CoreFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'core_form_submissionss',
            },
        ),
        migrations.CreateModel(
            name='CoreTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(choices=[('single_form', 'Single Form'), ('multi_step_form', 'Multi Step Form')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'core_templates',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'core_countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('decimal_digits', models.IntegerField()),
                ('rounding', models.IntegerField()),
                ('code', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'core_currencies',
            },
        ),
        migrations.CreateModel(
            name='CustomerInvitation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_customer_invitations',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('approvel_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_entities',
            },
        ),
        migrations.CreateModel(
            name='EntityApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('user', models.BigIntegerField(blank=True, null=True)),
                ('role', models.BigIntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.BigIntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_entity_approvals',
            },
        ),
        migrations.CreateModel(
            name='EntityApprovalRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('entity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('rule', models.JSONField(blank=True, null=True)),
                ('default_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'core_entity_approval_rules',
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#eeeeef', max_length=100)),
            ],
            options={
                'db_table': 'core_flags',
            },
        ),
        migrations.CreateModel(
            name='FlexField',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('entity_type', models.CharField(max_length=255)),
                ('field_code', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('field_label', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('data_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_fixed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'core_flex_fields',
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(default='crm', max_length=100)),
            ],
            options={
                'db_table': 'core_forms',
            },
        ),
        migrations.CreateModel(
            name='FormGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'core_form_groups',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('device', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login Histories',
                'db_table': 'core_login_histories',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=25, unique=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=320, null=True)),
            ],
            options={
                'db_table': 'core_modules',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'core_notifications',
            },
        ),
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#6B7280', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Type',
                'verbose_name_plural': 'Notification Types',
                'db_table': 'core_notification_types',
            },
        ),
        migrations.CreateModel(
            name='NotificationUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('notification_id', models.BigIntegerField(blank=True, null=True)),
                ('user_id', models.BigIntegerField(blank=True, null=True)),
                ('customer_id', models.BigIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(blank=True, null=True)),
                ('is_clear', models.BooleanField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification User',
                'verbose_name_plural': 'Notification Users',
                'db_table': 'core_notification_users',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_products',
            },
        ),
        migrations.CreateModel(
            name='ProductCoverage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('excess_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('limitation', models.CharField(blank=True, max_length=255, null=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('vendor_product_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_product_coverages',
            },
        ),
        migrations.CreateModel(
            name='ProductDocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('vendor_product_id', models.BigIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'core_product_document_types',
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_product_groups',
            },
        ),
        migrations.CreateModel(
            name='ProductGroupProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_group_id', models.BigIntegerField(blank=True, null=True)),
                ('product_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_product_group_products',
            },
        ),
        migrations.CreateModel(
            name='ProductVendorProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('product_id', models.BigIntegerField(blank=True, null=True)),
                ('vendor_product_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_product_vendor_products',
            },
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(db_index=True, max_length=255, unique=True)),
                ('type', models.CharField(max_length=255)),
                ('allows_custom_reason', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_reasons',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('module', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_services',
            },
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('contact_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'core_service_providers',
            },
        ),
        migrations.CreateModel(
            name='SettingKey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('attribute_name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'core_setting_keys',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(choices=[('Todo', 'To Do'), ('Inprogress', 'In Progress'), ('Done', 'Done')], max_length=20)),
                ('color', models.CharField(default='#eeeeef', max_length=100)),
                ('sort_index', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_task_status',
            },
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('team_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_team_users',
            },
        ),
        migrations.CreateModel(
            name='VendorProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('category_id', models.BigIntegerField(blank=True, null=True)),
                ('vendor_id', models.BigIntegerField(blank=True, null=True)),
                ('coverage_level', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency_id', models.BigIntegerField(blank=True, null=True)),
                ('premium_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deductible_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('claim_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('added_by', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('docs', models.CharField(blank=True, max_length=255, null=True)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_vendor_products',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_contact', models.CharField(max_length=20, null=True)),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('picture', models.TextField(blank=True, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('show_in_list', models.BooleanField(default=True)),
                ('duplicated_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='envoy.contact')),
            ],
            options={
                'db_table': 'core_contacts',
            },
        ),
        migrations.CreateModel(
            name='CoreFormCustomFormElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order_number', models.FloatField(blank=True, null=True)),
                ('column_size', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='envoy.coreformcustomformelement')),
                ('panel', models.ForeignKey(blank=True, db_column='panel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='envoy.coreformcustomformpanel')),
                ('step', models.ForeignKey(blank=True, db_column='step_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='envoy.coreformcustomformstep')),
            ],
            options={
                'db_table': 'core_form_custom_form_elements',
            },
        ),
        migrations.CreateModel(
            name='CoreFormCustomFormElementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.CharField(max_length=200)),
                ('element', models.ForeignKey(db_column='element_id', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='envoy.coreformcustomformelement')),
            ],
            options={
                'db_table': 'core_form_custom_form_element_options',
            },
        ),
        migrations.AddField(
            model_name='coreformcustomformpanel',
            name='step',
            field=models.ForeignKey(blank=True, db_column='step_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='envoy.coreformcustomformstep'),
        ),
        migrations.CreateModel(
            name='CoreFormDisplayElementValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('element', models.ForeignKey(db_column='element_id', on_delete=django.db.models.deletion.CASCADE, to='envoy.coreformcustomformelement')),
            ],
            options={
                'db_table': 'core_form_display_element_values',
            },
        ),
        migrations.CreateModel(
            name='CoreFormElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('element_group', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(choices=[('input_individual', 'Input Individual'), ('input_group', 'Input Group'), ('display', 'Display')], max_length=20)),
                ('code', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('group_element_order_number', models.FloatField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='envoy.coreformelement')),
            ],
            options={
                'db_table': 'core_form_elements',
            },
        ),
        migrations.AddField(
            model_name='coreformcustomformelement',
            name='element',
            field=models.ForeignKey(db_column='element_id', on_delete=django.db.models.deletion.CASCADE, to='envoy.coreformelement'),
        ),
        migrations.CreateModel(
            name='CoreFormGroupElementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_value', models.CharField(max_length=200)),
                ('element', models.ForeignKey(db_column='element_id', on_delete=django.db.models.deletion.CASCADE, to='envoy.coreformelement')),
            ],
            options={
                'db_table': 'core_form_group_element_options',
            },
        ),
        migrations.CreateModel(
            name='CoreFormSubmissionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('custom_form_element', models.ForeignKey(db_column='custom_form_element_id', on_delete=django.db.models.deletion.CASCADE, to='envoy.coreformcustomformelement')),
                ('form_element', models.ForeignKey(db_column='form_element_id', on_delete=django.db.models.deletion.CASCADE, to='envoy.coreformelement')),
                ('form_submission', models.ForeignKey(db_column='form_submission_id', on_delete=django.db.models.deletion.CASCADE, to='envoy.coreformsubmission')),
            ],
            options={
                'db_table': 'core_form_submission_valuess',
            },
        ),
        migrations.AddField(
            model_name='coreformsubmission',
            name='form',
            field=models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, to='envoy.coretemplate'),
        ),
        migrations.AddField(
            model_name='coreformcustomformstep',
            name='form',
            field=models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, to='envoy.coretemplate'),
        ),
        migrations.AddField(
            model_name='coreformcustomformpanel',
            name='form',
            field=models.ForeignKey(db_column='form_id', on_delete=django.db.models.deletion.CASCADE, to='envoy.coretemplate'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('type', models.CharField(choices=[('Corporate', 'Corporate'), ('Personal', 'Personal')], max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('logo', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('idp_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('portal_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='envoy.customer')),
                ('primary_contact', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='primary_accounts', to='envoy.contact')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='customers', to='envoy.entity')),
            ],
            options={
                'db_table': 'core_customers',
            },
        ),
        migrations.AddField(
            model_name='coreformsubmission',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='envoy.customer'),
        ),
        migrations.CreateModel(
            name='CustomerAdditionalContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='envoy.contact')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_contacts', to='envoy.customer')),
            ],
            options={
                'db_table': 'core_customer_contacts',
            },
        ),
        migrations.CreateModel(
            name='EntityDocument',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('doc', models.TextField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='envoy.entity')),
            ],
            options={
                'db_table': 'core_entity_docs',
            },
        ),
        migrations.CreateModel(
            name='FlexFieldOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('flex_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='envoy.flexfield')),
            ],
            options={
                'db_table': 'core_flex_field_options',
            },
        ),
        migrations.CreateModel(
            name='FlexValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('flex_values', models.JSONField(default=dict)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex_values', to='envoy.entity')),
            ],
            options={
                'db_table': 'core_flex_values',
            },
        ),
        migrations.CreateModel(
            name='FormAttribute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('TEXT', 'Text')], max_length=10)),
                ('attribute_name', models.CharField(blank=True, max_length=255, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='envoy.form')),
            ],
            options={
                'db_table': 'core_form_attributes',
            },
        ),
        migrations.CreateModel(
            name='FormGroupForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='envoy.form')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='envoy.formgroup')),
            ],
            options={
                'db_table': 'core_form_group_forms',
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='envoy.form')),
            ],
            options={
                'db_table': 'core_form_submissions',
            },
        ),
        migrations.CreateModel(
            name='FormSubmissionValue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formattributes', to='envoy.formattribute')),
                ('form_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formsubmissions', to='envoy.formsubmission')),
            ],
            options={
                'db_table': 'core_form_submission_values',
            },
        ),
        migrations.CreateModel(
            name='GroupContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envoy.contact')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envoy.contactgroup')),
            ],
            options={
                'db_table': 'core_group_contacts',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('remarks', models.CharField(blank=True, max_length=320, null=True)),
                ('can_be_permission', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='envoy.module')),
            ],
            options={
                'db_table': 'core_actions',
            },
        ),
        migrations.CreateModel(
            name='EntityReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(db_column='reason')),
                ('custom_reason', models.TextField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envoy.entity')),
                ('reason_fk', models.ForeignKey(blank=True, db_column='reason_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='envoy.reason')),
            ],
            options={
                'db_table': 'core_entity_reasons',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=320, null=True)),
                ('system_role', models.CharField(max_length=50, null=True)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='envoy.entity')),
            ],
            options={
                'db_table': 'core_roles',
            },
        ),
        migrations.CreateModel(
            name='RoleAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envoy.action')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envoy.role')),
            ],
            options={
                'db_table': 'core_role_authorities',
            },
        ),
        migrations.CreateModel(
            name='CoreUserBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('iban_swift_code', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_gateway_url', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp', to=settings.AUTH_USER_MODEL)),
                ('service_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='envoy.serviceprovider')),
            ],
            options={
                'db_table': 'core_user_bank_details',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_contact', models.CharField(max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_contacts', to='envoy.serviceprovider')),
            ],
            options={
                'db_table': 'core_service_provider_contacts',
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('setting_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_settings', to='envoy.settingkey')),
            ],
            options={
                'db_table': 'core_setting_global',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('module', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(default='#eeeeef', max_length=100)),
                ('sort_index', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status',
                'db_table': 'core_status',
                'unique_together': {('module', 'name')},
            },
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_status', to='envoy.status'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=20)),
                ('task', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('sort_index', models.FloatField(blank=True, null=True)),
                ('task_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tasks', to='envoy.taskstatus')),
            ],
            options={
                'db_table': 'core_tasks',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('leader_id', models.BigIntegerField(blank=True, null=True)),
                ('manager_id', models.BigIntegerField(blank=True, null=True)),
                ('detector_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='team_status', to='envoy.status')),
            ],
            options={
                'db_table': 'core_teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('first_name', models.CharField(max_length=80, null=True)),
                ('last_name', models.CharField(max_length=80, null=True)),
                ('display_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=80, null=True)),
                ('picture', models.TextField(max_length=300, null=True)),
                ('idp_user_id', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=100, null=True, unique=True)),
                ('cover_pic', models.TextField(max_length=300, null=True)),
                ('street_address', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('county', models.CharField(max_length=100, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='envoy.entity')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='envoy.role')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_status', to='envoy.status')),
            ],
            options={
                'db_table': 'core_users',
            },
        ),
        migrations.CreateModel(
            name='TaskStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='envoy.task')),
                ('task_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status_changes', to='envoy.taskstatus')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status_changes', to='envoy.user')),
            ],
            options={
                'db_table': 'core_task_status_histories',
            },
        ),
        migrations.CreateModel(
            name='TaskAssigneeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_histories', to='envoy.task')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assignee_changes', to='envoy.user')),
                ('from_assigned', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_from_history', to='envoy.user')),
                ('to_assigned', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_to_history', to='envoy.user')),
            ],
            options={
                'db_table': 'core_task_assignee_histories',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='envoy.user'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_provider_created', to='envoy.user'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_provider_updated', to='envoy.user'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider', to='envoy.user'),
        ),
        migrations.CreateModel(
            name='Intraction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('opportunity_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('opportunity_status_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='envoy.channel')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envoy.contact')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envoy.customer')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envoy.entity')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envoy.task')),
                ('contact_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='envoy.user')),
            ],
            options={
                'db_table': 'core_intractions',
            },
        ),
        migrations.CreateModel(
            name='EntityNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_high_priority', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='envoy.entity')),
                ('added_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envoy.user')),
            ],
            options={
                'db_table': 'core_entity_notes',
            },
        ),
        migrations.CreateModel(
            name='EntityActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='envoy.entity')),
                ('added_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='envoy.user')),
            ],
            options={
                'db_table': 'core_entity_activities',
            },
        ),
        migrations.AddField(
            model_name='entity',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entities_created', to='envoy.user'),
        ),
        migrations.AddField(
            model_name='entity',
            name='updated_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='entities_updated', to='envoy.user'),
        ),
        migrations.CreateModel(
            name='CoreServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('standardfee', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_type_created', to='envoy.user')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='service_type_updated', to='envoy.user')),
            ],
            options={
                'db_table': 'core_service_types',
            },
        ),
        migrations.CreateModel(
            name='CoreSalesTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('year_target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('month_target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('month_actual_sales_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('year_actual_sales_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envoy.user')),
            ],
            options={
                'db_table': 'core_sales_targets',
            },
        ),
        migrations.CreateModel(
            name='CoreOrganizationLevel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('level_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_levels', to='envoy.user')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_levels', to='envoy.user')),
            ],
            options={
                'db_table': 'core_organization_levels',
            },
        ),
        migrations.CreateModel(
            name='CoreOrganizationalNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('physical_address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=255)),
                ('contact_no', models.CharField(blank=True, max_length=80, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='envoy.coreorganizationalnode')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='organization_nodes', to='envoy.coreorganizationlevel')),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_nodes', to='envoy.user')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='updated_nodes', to='envoy.user')),
            ],
            options={
                'db_table': 'core_organizational_nodes',
            },
        ),
        migrations.CreateModel(
            name='CoreJobTitle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_title_created', to='envoy.user')),
                ('updated_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='job_title_updated', to='envoy.user')),
            ],
            options={
                'db_table': 'core_job_titles',
            },
        ),
        migrations.AddField(
            model_name='coreformsubmission',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='envoy.user'),
        ),
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='envoy.role')),
            ],
            options={
                'db_table': 'core_user_invitations',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('setting_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='envoy.settingkey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_setting_users',
            },
        ),
        migrations.CreateModel(
            name='EntityFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='envoy.entity')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entity_flags', to='envoy.flag')),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_reasons', to='envoy.reason')),
            ],
            options={
                'db_table': 'core_entity_flags',
                'unique_together': {('entity', 'flag')},
            },
        ),
        migrations.CreateModel(
            name='ProductTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_teams', to='envoy.product')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_products', to='envoy.team')),
            ],
            options={
                'db_table': 'core_product_teams',
                'unique_together': {('product', 'team')},
            },
        ),
    ]
