# Generated by Django 5.1.5 on 2025-07-22 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coreuserbankdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sp', to='envoy.user'),
        ),
    ]
