# Generated by Django 5.1.5 on 2025-07-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0002_alter_coreuserbankdetail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='approvel_status',
            field=models.BooleanField(default=False),
        ),
    ]
