# Generated by Django 5.1.5 on 2025-08-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0004_add_gmail_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField()),
                ('thread_id', models.CharField(blank=True, help_text='Gmail thread ID for replies', max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('conversation_code', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.IntegerField()),
                ('from_email', models.EmailField(help_text='Sender email address', max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('draft', 'Draft')], default='pending', max_length=20)),
                ('gmail_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('gmail_thread_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Email Message',
                'verbose_name_plural': 'Email Messages',
                'db_table': 'envoy_emailmessage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='gmailcredential',
            options={'verbose_name': 'Gmail Credential', 'verbose_name_plural': 'Gmail Credentials'},
        ),
        migrations.AlterModelTable(
            name='gmailcredential',
            table='envoy_gmailcredential',
        ),
    ]
