# Generated by Django 5.1.5 on 2025-08-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0005_add_email_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='subject',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='first_message_id',
            field=models.CharField(blank=True, help_text='ID of the first message in the thread', max_length=100, null=True),
        ),
    ]
