# Generated by Django 5.1.5 on 2025-08-11 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0006_remove_emailmessage_body_remove_emailmessage_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emailmessage',
            table='core_emailmessage',
        ),
        migrations.AlterModelTable(
            name='gmailcredential',
            table='core_gmailcredential',
        ),
    ]
