# Generated by Django 5.1.5 on 2025-08-11 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0007_alter_emailmessage_table_alter_gmailcredential_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailcredential',
            name='user',
            field=models.ForeignKey(default=1, help_text='User who owns this Gmail credential', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
