# Generated by Django 5.1.5 on 2025-08-12 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0008_gmailcredential_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='type_based_id',
            field=models.CharField(blank=True, help_text='ID of the first message in the thread', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='primary_contact',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='flexfield',
            name='data_type',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='flexfield',
            name='field_code',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='flexfield',
            name='field_label',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='intraction',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='entity',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.RESTRICT, to='envoy.entity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='taskstatushistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='status_changeby', to='envoy.user'),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='email',
            field=models.EmailField(max_length=320),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
