# Generated by Django 5.1.5 on 2025-08-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0009_emailmessage_type_based_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='insurer_id',
            field=models.CharField(blank=True, help_text='ID of the insurer for this perticular mail', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='type_based_id',
            field=models.CharField(blank=True, help_text='ID of the send message quotation or policy', max_length=100, null=True),
        ),
    ]
