# Generated by Django 5.1.5 on 2025-08-16 18:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0010_emailmessage_insurer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('type_based_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('gmail_thread_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('POLICY', 'POLICY'), ('QUOTATION', 'QUOTATION'), ('ENDORSEMENT', 'ENDORSEMENT')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to='envoy.serviceprovider')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations_created', to='envoy.user')),
            ],
            options={
                'db_table': 'core_chat_conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gmail_message_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('gmail_thread_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('first_message_id', models.CharField(blank=True, max_length=64, null=True)),
                ('from_email', models.TextField(blank=True, null=True)),
                ('to_email', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='envoy.chatconversation')),
            ],
            options={
                'db_table': 'core_email_messages',
                'ordering': ['sent_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_url', models.TextField(blank=True, null=True)),
                ('content_type', models.TextField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('gmail_attachment_id', models.CharField(blank=True, max_length=256, null=True)),
                ('is_image', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='envoy.emailchatmessage')),
            ],
            options={
                'db_table': 'core_email_attachments',
            },
        ),
    ]
