# Generated by Django 5.1.5 on 2025-08-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0012_increase_gmail_attachment_id_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailchatmessage',
            index=models.Index(fields=['conversation', 'sent_at'], name='core_email__convers_26e663_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchatmessage',
            index=models.Index(fields=['conversation', 'id'], name='core_email__convers_e479a9_idx'),
        ),
        migrations.AddIndex(
            model_name='emailchatmessage',
            index=models.Index(fields=['gmail_message_id'], name='core_email__gmail_m_e2f7d4_idx'),
        ),
    ]
