# Generated by Django 5.1.5 on 2025-08-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0013_add_email_message_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['email_message'], name='core_email__email_m_1bac74_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('gmail_attachment_id__isnull', False)), fields=('email_message', 'gmail_attachment_id'), name='uniq_email_gmail_attachment_when_present'),
        ),
    ]
