# Generated by Django 5.1.5 on 2025-08-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0014_add_attachment_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailattachment',
            name='uniq_email_gmail_attachment_when_present',
        ),
        migrations.AddIndex(
            model_name='emailattachment',
            index=models.Index(fields=['gmail_attachment_id'], name='core_email__gmail_a_12cd0b_idx'),
        ),
    ]
