# Generated by Django 5.1.5 on 2025-08-17 19:00

import envoy.models.email_attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0015_add_attachment_gmail_id_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=envoy.models.email_attachment.attachment_upload_path),
        ),
    ]
