# Generated by Django 5.1.5 on 2025-08-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0016_add_file_field_to_email_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_enrolled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
