# Generated by Django 5.1.6 on 2025-09-03 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0017_customer_is_enrolled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroupTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_group_teams', to='envoy.productgroup')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_product_groups', to='envoy.team')),
            ],
            options={
                'db_table': 'core_product_group_teams',
            },
        ),
    ]
