# Generated by Django 5.1.5 on 2025-09-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0018_productgroupteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='type',
        ),
        migrations.AddField(
            model_name='reason',
            name='type_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
