# Generated by Django 5.1.6 on 2025-09-22 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0019_remove_reason_type_reason_type_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_product_categories',
            },
        ),
        migrations.RenameField(
            model_name='productcoverage',
            old_name='limitation',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='productcoverage',
            name='coverage_amount',
        ),
        migrations.RemoveField(
            model_name='productcoverage',
            name='excess_amount',
        ),
        migrations.RemoveField(
            model_name='productcoverage',
            name='is_mandatory',
        ),
        migrations.AddField(
            model_name='productcoverage',
            name='type',
            field=models.ForeignKey(blank=True, db_column='type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='envoy.productcategory'),
        ),
    ]
