# Generated by Django 5.1.6 on 2025-10-21 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0020_productcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='envoy.currency'),
        ),
        migrations.AddField(
            model_name='serviceprovidercontact',
            name='contact_type',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
