# Generated by Django 4.2.7 on 2026-03-12 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0022_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailcredential',
            name='last_history_id',
            field=models.CharField(blank=True, help_text='Last processed Gmail historyId for Pub/Sub push sync', max_length=50, null=True),
        ),
    ]
