# Generated by Django 4.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envoy', '0023_gmailcredential_last_history_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchatmessage',
            name='is_seen',
            field=models.BooleanField(
                default=False,
                help_text='True when the user has seen this message (e.g. opened the conversation).',
            ),
        ),
    ]
