"""
Django settings for envoy_bu_policy_api project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("JWT_SECRET")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    # 'django.contrib.sessions',
    # 'django.contrib.messages',
    # 'django.contrib.staticfiles',
    'django_apscheduler',
    'envoy_bu_policy_api',
    'envoy_bu_policy_api.policy',
    'envoy_bu_policy_api.claims',
    'core_models',
    'envoy_bu_policy_api.finance',
    # 'djmigrator'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "envoy_bu_policy_api.middleware.MainAppJWTAuthMiddleware"
]

ROOT_URLCONF = 'envoy_bu_policy_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # "rest_framework_simplejwt.authentication.JWTAuthentication",
        "envoy_bu_policy_api.custom_auth_check.CustomJWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",  # Require authentication globally
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=7),  # Access token valid for 7 days
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),  # Refresh token valid for 30 days
    "ROTATE_REFRESH_TOKENS": True,  # Issue a new refresh token on refresh
    "BLACKLIST_AFTER_ROTATION": True,  # Blacklist old refresh tokens
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

WSGI_APPLICATION = 'envoy_bu_policy_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_DATABASE"),
        'USER': os.getenv("DB_USERNAME"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"), 
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATA_ANALYZER = os.getenv("DATA_ANALYZER")
ENVOYS3URL = os.getenv("ENVOYS3URL")

# Celery Configuration (Production - No Redis)
CELERY_TASK_ALWAYS_EAGER = True  # Execute tasks synchronously
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Schedule (1/2 hours) - UPDATED TO MATCH APSCHEDULER
CELERY_BEAT_SCHEDULE = {
    "update-policy-statuses-every-1-hour": {
        "task": "envoy_bu_policy_api.policy.tasks.update_policy_statuses",
        "schedule": 3600.0,  # Run every 1 hour (3600 seconds)
    },
    "update-credit-ages-every-2-hours": {
        "task": "envoy_bu_policy_api.policy.tasks.update_credit_ages",
        "schedule": 7200.0,  # Run every 2 hours (7200 seconds)
    },
}

# Django APScheduler Configuration (Production Scheduling)
APSCHEDULER_DATETIME_FORMAT = "N j, Y, f:s a"
APSCHEDULER_RUN_NOW_TIMEOUT = 25  # Seconds
SCHEDULER_DEFAULT = True

# APScheduler Auto-Start Configuration
# Set APSCHEDULER_AUTO_START=true in environment to enable auto-start
APSCHEDULER_AUTO_START = os.getenv('APSCHEDULER_AUTO_START', 'false').lower() in ('true', '1', 'yes')

# APScheduler Job Store Configuration
APSCHEDULER_JOB_DEFAULTS = {
    'coalesce': False,
    'max_instances': 1,
    'misfire_grace_time': 15,  # seconds
}

# Logging Configuration for Task Monitoring
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'task_format': {
            'format': '[{levelname}] {asctime} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/django.log',
            'formatter': 'verbose',
        },
        'task_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/task_execution.log',
            'formatter': 'task_format',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'policy_tasks': {
            'handlers': ['task_file'],  # File only - no console
            'level': 'INFO',
            'propagate': False,
        },
        'apscheduler_tasks': {
            'handlers': ['task_file'],  # File only - no console
            'level': 'INFO',
            'propagate': False,
        },
        'django_apscheduler': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'envoy_bu_policy_api.policy.tasks': {
            'handlers': ['task_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        'envoy_bu_policy_api.policy.apscheduler_tasks': {
            'handlers': ['task_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}