"""
Django settings for envoy project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
# import pymysql

# # from envoy.no_migrations import DisableMigrations
# pymysql.install_as_MySQLdb()
from datetime import timedelta

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("JWT_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = []

# MIGRATION_MODULES = DisableMigrations()



# Application definition

INSTALLED_APPS = [
    # "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    # "django.contrib.sessions",
    # "django.contrib.messages",
    # "django.contrib.staticfiles",
    "accounts",
    "envoy"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "envoy.middleware.EndpointPermissionMiddleware",
]

ROOT_URLCONF = "envoy.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.SessionAuthentication', 
        'envoy.custom_auth_check.CustomJWTAuthentication',  
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  
    ),
}

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")
GOOGLE_SCOPES = os.getenv("GOOGLE_SCOPES", "").split()
PAYMENT_CREATE_API_URL = os.getenv("PAYMENT_CREATE_API_URL")

BASE_URLS = {
    "BROKERAGE_FRONTEND_BASE_URL": os.getenv("BROKERAGE_FRONTEND_BASE_URL"),
    "CUSTOMER_FRONTEND_BASE_URL": os.getenv("CUSTOMER_FRONTEND_BASE_URL"),
    "EMAIL_SENDING_API_URL": os.getenv("EMAIL_SENDING_API_URL"),
    "EXTERNAL_API_URL": os.getenv("EXTERNAL_API_URL"),
    "CUSTOMER_REGISTRATION_API_URL": os.getenv("CUSTOMER_REGISTRATION_API_URL"),
    "CUSTOMER_RESET_PASSWAORD_API_URL" : os.getenv("CUSTOMER_RESET_PASSWAORD_API_URL")
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=365 * 10),  # 10 years
    "REFRESH_TOKEN_LIFETIME": timedelta(days=365 * 10),  # 10 years if needed
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",  # Ensure tokens store the correct user ID field
    "USER_ID_CLAIM": "user_id",
}

WSGI_APPLICATION = "envoy.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv("DB_DATABASE"),
        'USER': os.getenv("DB_USERNAME"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"), 
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "core.utils.CommonPagination",
    "PAGE_SIZE": 10,  # Default page size
}

# Get environment variables with defaults
BROKERAGE_FRONTEND_BASE_URL = os.getenv(
    "BROKERAGE_FRONTEND_BASE_URL"
)
CUSTOMER_FRONTEND_BASE_URL = os.getenv(
    "CUSTOMER_FRONTEND_BASE_URL"
)

# AWS S3 Configuration (for presigned URLs)
S3_ACCESS_KEY_ID = os.getenv("S3_ACCESS_KEY_ID")
S3_SECRET_ACCESS_KEY = os.getenv("S3_SECRET_ACCESS_KEY")
S3_BUCKET_NAME = os.getenv("S3_BUCKET_NAME")
S3_REGION = os.getenv("S3_REGION")
S3_ATTACHMENTS_FOLDER = os.getenv("mailattachments")

# CDN Configuration
CDN_BASE_URL = os.getenv("CDN_BASE_URL")  # e.g., "https://dev-cdn.envoy.apptimus.lk/envoy-test"
EMAIL_SENDING_API_URL = os.getenv(
    "EMAIL_SENDING_API_URL"
)
MAIL_MAILER = os.getenv("MAIL_MAILER")
MAIL_HOST = os.getenv("MAIL_HOST")
MAIL_PORT = int(os.getenv("MAIL_PORT", 587))
MAIL_USERNAME = os.getenv("MAIL_USERNAME")
MAIL_PASSWORD = os.getenv("MAIL_PASSWORD")
MAIL_FROM_ADDRESS = os.getenv("MAIL_FROM_ADDRESS")
MAIL_FROM_NAME = os.getenv("MAIL_FROM_NAME")
EMAIL_SENDING_API_URL = os.getenv("EMAIL_SENDING_API_URL")
EXTERNAL_API_URL = os.getenv("EXTERNAL_API_URL")
CUSTOMER_REGISTRATION_API_URL= os.getenv("CUSTOMER_REGISTRATION_API_URL")
CUSTOMER_RESET_PASSWAORD_API_URL = os.getenv("CUSTOMER_RESET_PASSWAORD_API_URL")
GENERATE_AUTH_KEY_API_URL = os.getenv("GENERATE_AUTH_KEY_API_URL")
IDP_BACKEND_APP_SECRET_KEY = os.getenv("IDP_BACKEND_APP_SECRET_KEY")
CUSTOMER_SP_CODE = os.getenv("CUSTOMER_SP_CODE")
CREDENTIALS_RESTORE_API_URL = os.getenv("CREDENTIALS_RESTORE_API_URL")
DB_DATABASE= os.getenv("DB_DATABASE")

