import localFont from 'next/font/local';
import '../../../public/styles/theme.css';
import '@apptimus-ui/theme/dist/components/styles/ynex/app.css';
import '../../../public/styles/custom.css';

const inter = localFont({
  src: [
    { path: '../../../public/fonts/Inter/Inter_18pt-Thin.ttf', weight: '100', style: 'normal' },
    { path: '../../../public/fonts/Inter/Inter_18pt-Light.ttf', weight: '300', style: 'normal' },
    { path: '../../../public/fonts/Inter/Inter_18pt-Regular.ttf', weight: '400', style: 'normal' },
    { path: '../../../public/fonts/Inter/Inter_18pt-Medium.ttf', weight: '500', style: 'normal' },
    { path: '../../../public/fonts/Inter/Inter_18pt-SemiBold.ttf', weight: '600', style: 'normal' },
    { path: '../../../public/fonts/Inter/Inter_18pt-Bold.ttf', weight: '700', style: 'normal' },
    { path: '../../../public/fonts/Inter/Inter_18pt-ExtraBold.ttf', weight: '800', style: 'normal' },
    { path: '../../../public/fonts/Inter/Inter_18pt-Black.ttf', weight: '900', style: 'normal' },
  ],
  variable: '--font-inter',
  display: 'swap',
});

export const metadata = {
  title: 'Vanguard X',
  // description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.variable}>
      <body>{children}</body>
    </html>
  );
}
