export const AsyncSelectConfigData = [
  {
    field: 'policies',
    widget: 'table',
    PREFIX: process.env.POLICY_PROXY_PREFIX,
    url: '/api/issued-policy',
    label: 'risk_type_name',
    id: 'id',
  },
  {
    field: 'sum_insureds',
    widget: 'table',
    PREFIX: process.env.POLICY_PROXY_PREFIX,
    url: '/api/issued-policy',
    label: 'risk_type_name',
    id: 'id',
  },
  {
    field: 'agent_commission',
    widget: 'table',
    PREFIX: process.env.POLICY_PROXY_PREFIX,
    url: 'api/agent-commissions',
    label: 'total_agent_commission',
    id: 'id',
  },
  {
    field: 'risk_type_id',
    widget: 'dropdown',
    PREFIX: process.env.POLICY_PROXY_PREFIX,
    url: 'api/risk-types',
    label: 'name',
    id: 'id',
  },
  {
    field: 'product_id',
    widget: 'dropdown',
    PREFIX: process.env.CORE_PROXY_PREFIX,
    url: 'api/insurer-products',
    label: 'name',
    id: 'id',
  },
  {
    field: 'insurer_id',
    widget: 'dropdown',
    PREFIX: process.env.CORE_PROXY_PREFIX,
    url: 'api/service-providers',
    label: 'name',
    id: 'id',
  },
  {
    field: 'status',
    widget: 'dropdown',
    PREFIX: process.env.CORE_PROXY_PREFIX,
    url: 'api/status',
    label: 'risk_type_name',
    id: 'id',
  },
  {
    field: 'role_id',
    widget: 'dropdown',
    PREFIX: process.env.CORE_PROXY_PREFIX,
    url: 'api/roles',
    label: 'name',
    id: 'id',
  },
  {
    field: 'agent_id',
    widget: 'dropdown',
    PREFIX: process.env.CORE_PROXY_PREFIX,
    url: 'api/users',
    label: 'display_name',
    id: 'id',
  },
];
