export const taskStatuses = [
  { id: 1, title: 'To Do', color: '#00800014', total_tasks: 50 },
  { id: 2, title: 'On Progress', color: 'rgb(0 188 212 / 14%)', total_tasks: 24 },
  { id: 3, title: 'Done', color: '#ff00002e', total_tasks: 12 },
  // { id: 4, title: 'Reopen', color: '#0000ff26', total_tasks: 14 },
];

export const tasks = [
  { id: 1, title: 'Make a initial call', status: 1 },
  { id: 2, title: 'Send the proposal', status: 1 },
  { id: 3, title: 'Follow up', status: 1 },
  { id: 4, title: 'Close the deal', status: 1 },
  { id: 5, title: 'Send the invoice', status: 1 },
  { id: 6, title: 'Get the payment', status: 1 },
  { id: 7, title: 'Complete the project', status: 1 },
  { id: 8, title: 'Get the feedback', status: 1 },
  { id: 9, title: 'Close the project', status: 1 },
  { id: 10, title: 'Get the referral', status: 1 },
  { id: 11, title: 'Send the thank you note', status: 1 },
  { id: 12, title: 'Get the testimonial', status: 1 },
  { id: 13, title: 'Share the success story', status: 1 },
  { id: 14, title: 'Celebrate the success', status: 1 },
  { id: 15, title: 'Plan for the next', status: 1 },
  { id: 16, title: 'Get the repeat business', status: 1 },
  { id: 17, title: 'Get the referral', status: 1 },
  { id: 18, title: 'Send the thank you note', status: 1 },
  { id: 19, title: 'Get the testimonial', status: 1 },
  { id: 20, title: 'Share the success story', status: 1 },
  { id: 21, title: 'Celebrate the success', status: 1 },
  { id: 22, title: 'Plan for the next', status: 1 },
  { id: 23, title: 'Get the repeat business', status: 1 },
  { id: 24, title: 'Get the referral', status: 1 },
  { id: 25, title: 'Send the thank you note', status: 1 },
  { id: 26, title: 'Get the testimonial', status: 1 },
  { id: 27, title: 'Share the success story', status: 1 },
  { id: 28, title: 'Celebrate the success', status: 1 },
  { id: 29, title: 'Plan for the next', status: 1 },
  { id: 30, title: 'Get the repeat business', status: 1 },
  { id: 31, title: 'Get the referral', status: 1 },
  { id: 32, title: 'Send the thank you note', status: 1 },
  { id: 33, title: 'Get the testimonial', status: 1 },
  { id: 34, title: 'Share the success story', status: 1 },
  { id: 35, title: 'Celebrate the success', status: 1 },
  { id: 36, title: 'Plan for the next', status: 1 },
  { id: 37, title: 'Get the repeat business', status: 1 },
  { id: 38, title: 'Get the referral', status: 1 },
  { id: 39, title: 'Send the thank you note', status: 1 },
  { id: 40, title: 'Get the testimonial', status: 1 },
  { id: 41, title: 'Share the success story', status: 1 },
  { id: 42, title: 'Celebrate the success', status: 1 },
  { id: 43, title: 'Plan for the next', status: 1 },
  { id: 44, title: 'Get the repeat business', status: 1 },
  { id: 45, title: 'Get the referral', status: 1 },
  { id: 46, title: 'Send the thank you note', status: 1 },
  { id: 47, title: 'Get the testimonial', status: 1 },
  { id: 48, title: 'Share the success story', status: 1 },
  { id: 49, title: 'Celebrate the success', status: 1 },
  { id: 50, title: 'Plan for the next', status: 1 },
  { id: 51, title: 'Get the repeat business', status: 2 },
  { id: 52, title: 'Get the referral', status: 2 },
  { id: 53, title: 'Send the thank you note', status: 2 },
  { id: 54, title: 'Get the testimonial', status: 2 },
  { id: 55, title: 'Share the success story', status: 2 },
  { id: 56, title: 'Celebrate the success', status: 2 },
  { id: 57, title: 'Plan for the next', status: 2 },
  { id: 58, title: 'Get the repeat business', status: 2 },
  { id: 59, title: 'Get the referral', status: 2 },
  { id: 60, title: 'Send the thank you note', status: 2 },
  { id: 61, title: 'Get the testimonial', status: 2 },
  { id: 62, title: 'Share the success story', status: 2 },
  { id: 63, title: 'Celebrate the success', status: 2 },
  { id: 64, title: 'Plan for the next', status: 2 },
  { id: 65, title: 'Get the repeat business', status: 2 },
  { id: 66, title: 'Get the referral', status: 2 },
  { id: 67, title: 'Send the thank you note', status: 2 },
  { id: 68, title: 'Get the testimonial', status: 2 },
  { id: 69, title: 'Share the success story', status: 2 },
  { id: 70, title: 'Celebrate the success', status: 2 },
  { id: 71, title: 'Plan for the next', status: 2 },
  { id: 72, title: 'Get the repeat business', status: 2 },
  { id: 73, title: 'Get the referral', status: 2 },
  { id: 74, title: 'Send the thank you note', status: 2 },
  { id: 75, title: 'Get the testimonial', status: 3 },
  { id: 76, title: 'Share the success story', status: 3 },
  { id: 77, title: 'Celebrate the success', status: 3 },
  { id: 78, title: 'Plan for the next', status: 3 },
  { id: 79, title: 'Get the repeat business', status: 3 },
  { id: 80, title: 'Get the referral', status: 3 },
  { id: 81, title: 'Send the thank you note', status: 3 },
  { id: 82, title: 'Get the testimonial', status: 3 },
  { id: 83, title: 'Share the success story', status: 3 },
  { id: 84, title: 'Celebrate the success', status: 3 },
  { id: 85, title: 'Plan for the next', status: 3 },
  { id: 86, title: 'Get the repeat business', status: 3 },
  { id: 87, title: 'Get the referral', status: 4 },
  { id: 88, title: 'Send the thank you note', status: 4 },
  { id: 89, title: 'Get the testimonial', status: 4 },
  { id: 90, title: 'Share the success story', status: 4 },
  { id: 91, title: 'Celebrate the success', status: 4 },
  { id: 92, title: 'Plan for the next', status: 4 },
  { id: 93, title: 'Get the repeat business', status: 4 },
  { id: 94, title: 'Get the referral', status: 4 },
  { id: 95, title: 'Send the thank you note', status: 4 },
  { id: 96, title: 'Get the testimonial', status: 4 },
  { id: 97, title: 'Share the success story', status: 4 },
  { id: 98, title: 'Celebrate the success', status: 4 },
  { id: 99, title: 'Plan for the next', status: 4 },
  { id: 100, title: 'Get the repeat business', status: 4 },
];
